### ISSUE TITLE
Charts - Upgrade AuthProxy and use open source version

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/community#366]
If the latest PR's from @aiciobanu have been accepted and merged in, we need to adjust the Flow helm chart to reference and utilize this version of the Auth Proxy.

As well as document the differences i.e. if you are using the basic auth from here then you need to do x

**Comment by tlawrie** [comment]
From @aiciobanu - Passing custom templates for error.html and sign_in.html  when the  auth mode is set to basic I’ve tested it using the 6.9.1 chart version from OAuth2 Proxy, and got the following steps:
Apply the attached ConfigMap  - oauth2-proxy-custom-templates-configmap.yaml
Add the following fields in the values file (OAuth2 Proxy's values):
```
extraArgs:
  custom-templates-dir: /custom/templates
extraVolumes:
  - name: custom-templates
    configMap:
      name: oauth2-proxy-custom-templates
extraVolumeMounts:
  - name: custom-templates
    mountPath: /custom/templates
```
